import type { Page } from '@playwright/test'
import { installPerfInstrumentation } from './instrument'

/** Where browser-mode Studio serves from; the Playwright config owns starting it. */
export const BASE_URL = process.env.PERF_BASE_URL ?? 'http://localhost:1420'

/** Ids and names generated by `mock-data/perf-fixtures.ts`. */
export const PERF = {
	primaryConnection: 'perf-conn-00',
	secondaryConnection: 'perf-conn-01',
	largeTable: 'perf_events',
	smallTables: ['perf_accounts', 'perf_regions'] as const
}

/**
 * Selectors the harness drives. All of them are markup the product already
 * ships — accessible names and a data attribute — so the harness needs no test
 * hooks added to product code.
 */
export const SELECTORS = {
	navItem(label: string): string {
		return `[role="menuitem"][aria-label="${label}"]`
	},
	tableItem(name: string): string {
		return `[role="treeitem"][aria-label^="${name},"]`
	},
	connectionTrigger: 'button[aria-label^="Change database connection"]',
	connectionItem(id: string): string {
		return `[data-connection-id="${id}"]`
	},
	grid: 'table[role="grid"]',
	editor: '.monaco-editor',
	cell: '[data-cell-key="0:1"]'
}

export const NAV = {
	dataViewer: 'Data Viewer',
	sqlConsole: 'SQL Console'
}

/**
 * Boots browser-mode Studio with the perf fixtures loaded and the
 * instrumentation installed, and waits until the grid has painted.
 *
 * The two init scripts run before any application code: the first installs the
 * React and long-frame probes, the second sets the storage flags the mock data
 * module reads at import time.
 */
export async function bootPerfApp(page: Page): Promise<void> {
	await page.addInitScript(installPerfInstrumentation)
	await page.addInitScript(function seedFlags() {
		try {
			localStorage.setItem('dora_perf_fixtures', '1')
			localStorage.setItem('dora_has_seen_scroll_hint', 'true')
			// The first-run tour renders a modal over the app and would eat the
			// clicks every scenario depends on.
			localStorage.setItem('dora_onboarding_tour_completed', '1')
			sessionStorage.setItem('dora_demo_notice_dismissed', 'true')
		} catch (error) {
			console.warn('[perf] storage unavailable', error)
		}
	})

	await page.goto(
		`${BASE_URL}/?view=database-studio&connection=${PERF.primaryConnection}&perf=1`,
		{ waitUntil: 'domcontentloaded' }
	)

	await page.waitForSelector(SELECTORS.cell, { timeout: 60_000 })
	await settle(page)
}

/** Two animation frames — enough for layout and paint to have happened. */
export async function settle(page: Page): Promise<void> {
	await page.evaluate(function waitTwoFrames() {
		return new Promise<void>(function resolver(resolve) {
			requestAnimationFrame(function first() {
				requestAnimationFrame(function second() {
					resolve()
				})
			})
		})
	})
}

export async function commitCount(page: Page): Promise<number> {
	return page.evaluate(function readCommits() {
		const state = (window as unknown as Record<string, { commits: number[] }>).__doraPerf
		return state ? state.commits.length : -1
	})
}

export async function monacoCreations(page: Page): Promise<number> {
	return page.evaluate(function readMonaco() {
		const state = (window as unknown as Record<string, { monacoCreations: number }>).__doraPerf
		return state ? state.monacoCreations : -1
	})
}

/**
 * How many times the mock adapter has been called, by method. The mock adapter
 * installs this counter; it is how "zero IPC" is asserted literally rather than
 * inferred from a timing.
 */
export async function adapterCalls(page: Page, method: string): Promise<number> {
	return page.evaluate(function readCalls(name) {
		const counts = (window as unknown as { __doraAdapterCalls?: Record<string, number> })
			.__doraAdapterCalls
		return counts ? (counts[name] ?? 0) : -1
	}, method)
}

/** Parks a node on `window` so a later step can ask whether it survived. */
export async function trackNode(page: Page, selector: string): Promise<boolean> {
	return page.evaluate(function park(sel) {
		const state = (window as unknown as Record<string, { tracked: Element | null }>).__doraPerf
		const node = document.querySelector(sel)
		if (!state || !node) return false
		state.tracked = node
		return true
	}, selector)
}

/** True when the parked node is still in the document. */
export async function trackedNodeSurvives(page: Page): Promise<boolean> {
	return page.evaluate(function check() {
		const state = (window as unknown as Record<string, { tracked: Element | null }>).__doraPerf
		return Boolean(state && state.tracked && state.tracked.isConnected)
	})
}
