use tauri_specta::{collect_commands, Builder};

pub fn generate_bindings() -> Builder<tauri::Wry> {
    use crate::database::commands as db_commands;
    use crate::window::commands as window_commands;

    Builder::<tauri::Wry>::new().commands(collect_commands![
        // Window commands
        window_commands::minimize_window,
        window_commands::maximize_window,
        window_commands::close_window,
        window_commands::open_sqlite_db,
        window_commands::save_sqlite_db,
        window_commands::open_file,
        // Database commands
        db_commands::add_connection,
        db_commands::update_connection,
        db_commands::update_connection_color,
        db_commands::connect_to_database,
        db_commands::disconnect_from_database,
        db_commands::get_connections,
        db_commands::remove_connection,
        db_commands::test_connection,
        db_commands::initialize_connections,
        db_commands::get_recent_connections,
        db_commands::get_connection_history,
        db_commands::set_connection_pin,
        db_commands::verify_pin_and_get_credentials,
        db_commands::start_query,
        db_commands::fetch_query,
        db_commands::fetch_page,
        db_commands::get_query_status,
        db_commands::get_page_count,
        db_commands::get_columns,
        db_commands::save_query_to_history,
        db_commands::get_query_history,
        db_commands::start_live_monitor,
        db_commands::stop_live_monitor,
        db_commands::get_recent_queries,
        db_commands::save_script,
        db_commands::update_script,
        db_commands::get_scripts,
        db_commands::delete_script,
        db_commands::get_snippets,
        db_commands::save_snippet,
        db_commands::update_snippet,
        db_commands::delete_snippet,
        db_commands::seed_system_snippets,
        db_commands::get_snippet_folders,
        db_commands::create_snippet_folder,
        db_commands::update_snippet_folder,
        db_commands::delete_snippet_folder,
        db_commands::save_session_state,
        db_commands::get_session_state,
        db_commands::get_setting,
        db_commands::set_setting,
        db_commands::insert_row,
        db_commands::update_cell,
        db_commands::delete_rows,
        db_commands::duplicate_row,
        db_commands::export_table,
        db_commands::soft_delete_rows,
        db_commands::undo_soft_delete,
        db_commands::truncate_table,
        db_commands::truncate_database,
        db_commands::dump_database,
        db_commands::execute_batch,
        db_commands::get_database_schema,
        db_commands::get_database_metadata,
        db_commands::seed_table,
        db_commands::parse_sql,
        db_commands::build_sql,
        db_commands::export_schema_sql,
        db_commands::export_schema_drizzle,
        db_commands::ai_complete,
        db_commands::ai_set_provider,
        db_commands::ai_get_provider,
        db_commands::ai_set_gemini_key,
        db_commands::ai_configure_ollama,
        db_commands::ai_list_ollama_models
    ])
}

/// Export TypeScript bindings to the frontend.
pub fn export_ts_bindings() {
    generate_bindings()
        .export(
            specta_typescript::Typescript::default()
                .bigint(specta_typescript::BigIntExportBehavior::Number)
                .header("// @ts-nocheck\n// Auto-generated by tauri-specta. DO NOT EDIT.\n\n"),
            "../src/lib/bindings.ts",
        )
        .expect("Failed to export TypeScript bindings");
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    #[ignore]
    fn export_bindings() {
        export_ts_bindings();
    }
}
