import type { ColumnDefinition, TableData } from '../types'

/**
 * Returns a new TableData with the rows whose primary key matches one of
 * `primaryKeyValues` removed, adjusting `totalCount` accordingly. Used to drop
 * rows from the grid optimistically before the delete mutation resolves. The
 * original object is returned unchanged when nothing matches.
 */
export function removeRowsByPrimaryKey(
	tableData: TableData,
	primaryKeyColumn: string,
	primaryKeyValues: unknown[]
): TableData {
	const removed = new Set(primaryKeyValues)
	const rows = tableData.rows.filter(function (row) {
		return !removed.has(row[primaryKeyColumn])
	})
	if (rows.length === tableData.rows.length) return tableData
	const removedCount = tableData.rows.length - rows.length
	return {
		...tableData,
		rows,
		totalCount: Math.max(0, tableData.totalCount - removedCount)
	}
}

/**
 * Returns a new TableData with `newRows` appended and `totalCount` bumped. Used
 * to show duplicated/inserted rows in the grid optimistically before the insert
 * mutation resolves; a later reload swaps them for the authoritative rows
 * (including server-generated primary keys). The original object is returned
 * unchanged when there's nothing to add.
 */
export function appendRows(
	tableData: TableData,
	newRows: Record<string, unknown>[]
): TableData {
	if (newRows.length === 0) return tableData
	return {
		...tableData,
		rows: [...tableData.rows, ...newRows],
		totalCount: tableData.totalCount + newRows.length
	}
}

/**
 * Best-effort default value for a single column. The grid has no access to the
 * database's declared DEFAULT, so this infers a sensible one: now() for
 * date/time columns and audit columns, null for nullable columns, and an empty
 * string for everything else. Used when clearing a cell back to its default.
 */
export function getColumnDefault(column: ColumnDefinition): unknown {
	const type = column.type.toLowerCase()
	const name = column.name.toLowerCase()
	if (type.includes('timestamp') || type.includes('datetime') || type.includes('date')) {
		return new Date().toISOString()
	}
	if (name.includes('created') || name.includes('updated') || name === 'date') {
		return new Date().toISOString()
	}
	return column.nullable ? null : ''
}

/**
 * Whether an insert may leave this primary key out and let the database fill
 * it in. True when introspection reported an auto-increment/identity column or
 * a DEFAULT expression; without that signal, integer and serial keys are
 * assumed to be generated and every other type (text, uuid without a default,
 * ...) is assumed to be a natural key the user has to supply.
 */
export function isGeneratedPrimaryKey(column: ColumnDefinition): boolean {
	if (!column.primaryKey) return false
	if (column.autoGenerated) return true
	const type = column.type.toLowerCase()
	return type.includes('int') || type.includes('serial')
}

export function createDefaultValues(columns: ColumnDefinition[]): Record<string, unknown> {
	const defaults: Record<string, unknown> = {}

	for (const col of columns) {
		if (isGeneratedPrimaryKey(col)) continue
		defaults[col.name] = col.primaryKey ? '' : getColumnDefault(col)
	}

	return defaults
}

/**
 * Prepares a row to be inserted as a copy of `row`: generated primary keys are
 * dropped so the database assigns a fresh one, while a natural primary key is
 * blanked so the user is prompted for a new value instead of colliding.
 */
export function buildDuplicateRow(
	row: Record<string, unknown>,
	columns: ColumnDefinition[]
): Record<string, unknown> {
	const copy = { ...row }
	for (const col of columns) {
		if (!col.primaryKey) continue
		if (isGeneratedPrimaryKey(col)) {
			delete copy[col.name]
		} else {
			copy[col.name] = ''
		}
	}
	return copy
}

/**
 * Whether rows of this table can be copied without user input, i.e. every
 * primary key column is generated by the database.
 */
export function canDuplicateWithoutInput(columns: ColumnDefinition[]): boolean {
	return columns.filter((c) => c.primaryKey).every(isGeneratedPrimaryKey)
}

export function normalizeValueForInsert(column: ColumnDefinition, value: unknown): unknown {
	const type = column.type.toLowerCase()
	const isIntegerType = type.includes('int') || type.includes('serial')
	const isFloatType =
		type.includes('float') ||
		type.includes('double') ||
		type.includes('decimal') ||
		type.includes('numeric')
	const isBooleanType = type.includes('bool')
	const isJsonType = type.includes('json')

	if (value === null || value === undefined) {
		return column.nullable ? null : value
	}

	if (typeof value === 'string') {
		const trimmed = value.trim()

		if (trimmed === '') {
			if (column.nullable) return null
			if (isIntegerType || isFloatType) return 0
			if (isBooleanType) return false
			return ''
		}

		if (isIntegerType) {
			const parsed = Number.parseInt(trimmed, 10)
			if (Number.isNaN(parsed)) return column.nullable ? null : 0
			// BIGINT values beyond JS's safe-integer range lose precision as a
			// number, so keep the literal string and let the database parse it
			// exactly. Every adapter accepts string-encoded numerics (Postgres
			// via `$1::text::<type>`, SQLite/libSQL via affinity, MySQL via
			// implicit coercion).
			if (!Number.isSafeInteger(parsed)) return trimmed
			return parsed
		}

		if (isFloatType) {
			const parsed = Number.parseFloat(trimmed)
			if (Number.isNaN(parsed)) return column.nullable ? null : 0
			// High-precision decimals exceed f64 (~15-17 significant digits);
			// keep the literal so the value is not silently rounded.
			const significantDigits = trimmed.replace(/[^0-9]/g, '').replace(/^0+/, '').length
			if (significantDigits > 15) return trimmed
			return parsed
		}

		if (isBooleanType) {
			const normalized = trimmed.toLowerCase()
			return (
				normalized === 'true' ||
				normalized === '1' ||
				normalized === 't' ||
				normalized === 'yes' ||
				normalized === 'on'
			)
		}

		if (isJsonType) {
			try {
				return JSON.parse(trimmed)
			} catch {
				return trimmed
			}
		}

		return value
	}

	return value
}

export function normalizeRowForInsert(
	rowData: Record<string, unknown>,
	columns: ColumnDefinition[]
): Record<string, unknown> {
	const byName = new Map(
		columns.map(function (column) {
			return [column.name, column] as const
		})
	)
	const normalized: Record<string, unknown> = {}

	for (const [key, value] of Object.entries(rowData)) {
		const column = byName.get(key)
		normalized[key] = column ? normalizeValueForInsert(column, value) : value
	}

	return normalized
}

export function rowsToCsv(rows: Record<string, unknown>[], columns?: string[]): string {
	if (rows.length === 0) return ''
	const headers = columns ?? Object.keys(rows[0])

	const csvRows = [
		headers.join(','),
		...rows.map(function (row) {
			return headers
				.map(function (header) {
					const value = row[header]
					if (value === null || value === undefined) return ''
					const stringValue = String(value)
					if (
						stringValue.includes(',') ||
						stringValue.includes('"') ||
						stringValue.includes('\n')
					) {
						return `"${stringValue.replace(/"/g, '""')}"`
					}
					return stringValue
				})
				.join(',')
		})
	]

	return csvRows.join('\n')
}

/**
 * Splits a SQL script into individual statements on top-level semicolons,
 * honouring single/double-quoted strings and line comments. Used to feed a
 * restored `.sql` dump to the batch-execute command.
 */
export function splitSqlStatements(sql: string): string[] {
	const statements: string[] = []
	let current = ''
	let inSingle = false
	let inDouble = false
	let inLineComment = false

	for (let i = 0; i < sql.length; i++) {
		const char = sql[i]

		if (inLineComment) {
			if (char === '\n') inLineComment = false
			current += char
			continue
		}

		if (!inSingle && !inDouble && char === '-' && sql[i + 1] === '-') {
			inLineComment = true
			current += char
			continue
		}

		if (char === "'" && !inDouble) inSingle = !inSingle
		else if (char === '"' && !inSingle) inDouble = !inDouble

		if (char === ';' && !inSingle && !inDouble) {
			if (current.trim()) statements.push(current.trim())
			current = ''
			continue
		}

		current += char
	}

	if (current.trim()) statements.push(current.trim())
	return statements
}

/** Renders a single value as a SQL literal for an INSERT statement. */
function toSqlLiteral(value: unknown): string {
	if (value === null || value === undefined) return 'NULL'
	if (typeof value === 'number') return Number.isFinite(value) ? String(value) : 'NULL'
	if (typeof value === 'boolean') return value ? 'TRUE' : 'FALSE'
	if (typeof value === 'object') {
		return `'${JSON.stringify(value).replace(/'/g, "''")}'`
	}
	return `'${String(value).replace(/'/g, "''")}'`
}

/**
 * Builds `INSERT INTO` statements for the given rows. Used by the data-grid
 * export so the exported SQL reflects the rows actually fetched (i.e. after any
 * active filters and sort are applied).
 */
export function rowsToSqlInsert(
	rows: Record<string, unknown>[],
	tableName: string,
	columns?: string[]
): string {
	if (rows.length === 0) return ''
	const headers = columns ?? Object.keys(rows[0])
	const columnList = headers.map((header) => `"${header}"`).join(', ')

	return rows
		.map(function (row) {
			const values = headers.map((header) => toSqlLiteral(row[header])).join(', ')
			return `INSERT INTO "${tableName}" (${columnList}) VALUES (${values});`
		})
		.join('\n')
}
