// @ts-nocheck
// Auto-generated by tauri-specta. DO NOT EDIT.


// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async minimizeWindow() : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("minimize_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async maximizeWindow() : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("maximize_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async closeWindow() : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openSqliteDb() : Promise<Result<string | null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_sqlite_db") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveSqliteDb() : Promise<Result<string | null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_sqlite_db") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openFile(title: string | null) : Promise<Result<string | null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_file", { title }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Multi-select picker for flat data files (CSV / TSV / Parquet / JSON) that
 * can be opened as a read-only DuckDB-backed connection.
 */
async openDataFiles() : Promise<Result<string[], { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_data_files") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read the first bytes of a database file and identify SQLite vs DuckDB.
 */
async probeDatabaseFile(path: string) : Promise<Result<DatabaseFileKind, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("probe_database_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pickFolder() : Promise<Result<string | null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pick_folder") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readProjectFile(path: string) : Promise<Result<string, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_project_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listDir(path: string) : Promise<Result<string[], { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_dir", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addConnection(name: string, databaseInfo: DatabaseInfo, color: number | null) : Promise<Result<ConnectionInfo, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_connection", { name, databaseInfo, color }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateConnection(connId: string, name: string, databaseInfo: DatabaseInfo, color: number | null) : Promise<Result<ConnectionInfo, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_connection", { connId, name, databaseInfo, color }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateConnectionColor(connectionId: string, color: number | null) : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_connection_color", { connectionId, color }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async connectToDatabase(connectionId: string) : Promise<Result<DatabaseConnectResult, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("connect_to_database", { connectionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDataFileSourceStatus(connectionId: string) : Promise<Result<DataFileSourceEntry[], { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_data_file_source_status", { connectionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async retryDataFileRegistration(connectionId: string) : Promise<Result<DatabaseConnectResult, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("retry_data_file_registration", { connectionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveDataFileSessionAsDuckdb(connectionId: string, destinationPath: string, overwrite: boolean) : Promise<Result<SaveDataFileSessionResult, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_data_file_session_as_duckdb", { connectionId, destinationPath, overwrite }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importFilesIntoDuckdb(connectionId: string, filePaths: string[]) : Promise<Result<ImportFilesIntoDuckDbResult, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_files_into_duckdb", { connectionId, filePaths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async disconnectFromDatabase(connectionId: string) : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("disconnect_from_database", { connectionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getConnections() : Promise<Result<ConnectionInfo[], { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_connections") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeConnection(connectionId: string) : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_connection", { connectionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async testConnection(databaseInfo: DatabaseInfo, connectionId: string | null) : Promise<Result<boolean, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("test_connection", { databaseInfo, connectionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async initializeConnections() : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("initialize_connections") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getRecentConnections(limit: number | null) : Promise<Result<ConnectionInfo[], { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_recent_connections", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getConnectionHistory(dbTypeFilter: string | null, successFilter: boolean | null, limit: number | null) : Promise<Result<ConnectionHistoryEntry[], { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_connection_history", { dbTypeFilter, successFilter, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async supabaseSaveToken(token: string) : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("supabase_save_token", { token }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async supabaseOauthConnect() : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("supabase_oauth_connect") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async supabaseListProjects() : Promise<Result<SupabaseProject[], { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("supabase_list_projects") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The Supabase organizations the stored token can access, so the UI can show
 * which account is currently connected.
 */
async supabaseAccount() : Promise<Result<SupabaseOrganization[], { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("supabase_account") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async supabasePoolerHost(projectRef: string) : Promise<Result<string, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("supabase_pooler_host", { projectRef }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async supabaseDisconnect() : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("supabase_disconnect") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async supabaseIsConnected() : Promise<boolean> {
    return await TAURI_INVOKE("supabase_is_connected");
},
async supabaseSaveProjectPassword(projectRef: string, password: string) : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("supabase_save_project_password", { projectRef, password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async supabaseGetProjectPassword(projectRef: string) : Promise<Result<string | null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("supabase_get_project_password", { projectRef }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async tursoSaveToken(token: string) : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("turso_save_token", { token }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async tursoListDatabases() : Promise<Result<TursoDatabase[], { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("turso_list_databases") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async tursoCreateToken(organizationSlug: string, databaseName: string) : Promise<Result<string, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("turso_create_token", { organizationSlug, databaseName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async tursoDisconnect() : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("turso_disconnect") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async tursoIsConnected() : Promise<boolean> {
    return await TAURI_INVOKE("turso_is_connected");
},
/**
 * Whether the Turso CLI is installed locally, so the frontend can offer
 * one-click minting instead of a manual token paste.
 */
async tursoCliAvailable() : Promise<boolean> {
    return await TAURI_INVOKE("turso_cli_available");
},
/**
 * Mints a Turso Platform API token via the local CLI (running `turso auth
 * login` first if the user isn't signed in), then validates and stores it.
 */
async tursoMintToken() : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("turso_mint_token") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Installs the Turso CLI via the official install script. macOS/Linux only —
 * returns an error on Windows with Scoop instructions.
 */
async tursoInstallCli() : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("turso_install_cli") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Whether the user is signed in to the local Turso CLI, so the frontend can
 * prompt for sign-in before offering one-click minting.
 */
async tursoCliLoggedIn() : Promise<boolean> {
    return await TAURI_INVOKE("turso_cli_logged_in");
},
/**
 * Runs `turso auth login` (opens a browser) so the user can authenticate the
 * Turso CLI without leaving Dora.
 */
async tursoCliLogin() : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("turso_cli_login") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The Turso organizations the stored token can access, so the UI can show
 * which account is currently connected.
 */
async tursoAccount() : Promise<Result<TursoOrganization[], { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("turso_account") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async neonSaveToken(token: string) : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("neon_save_token", { token }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async neonListDatabases() : Promise<Result<NeonDatabase[], { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("neon_list_databases") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Lists every branch of a Neon project so the user can connect to a non-primary
 * branch (e.g. a preview branch) instead of always landing on the default one.
 */
async neonListBranches(projectId: string) : Promise<Result<NeonBranch[], { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("neon_list_branches", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The Neon account the stored key belongs to, so the UI can show which account
 * is currently connected.
 */
async neonAccount() : Promise<Result<NeonAccount, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("neon_account") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async neonCreateConnectionUri(projectId: string, branchId: string, databaseName: string, roleName: string) : Promise<Result<string, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("neon_create_connection_uri", { projectId, branchId, databaseName, roleName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async neonDisconnect() : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("neon_disconnect") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async neonIsConnected() : Promise<boolean> {
    return await TAURI_INVOKE("neon_is_connected");
},
async cloudflareSaveToken(token: string) : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cloudflare_save_token", { token }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The Cloudflare accounts the stored token can see — the first pick step (D1 is
 * account-scoped) and the source of the "Connected as …" label.
 */
async cloudflareListAccounts() : Promise<Result<CloudflareAccount[], { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cloudflare_list_accounts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The D1 databases in one Cloudflare account.
 */
async cloudflareListDatabases(accountId: string) : Promise<Result<CloudflareD1Database[], { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cloudflare_list_databases", { accountId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cloudflareAccount() : Promise<Result<CloudflareAccount[], { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cloudflare_account") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cloudflareDisconnect() : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cloudflare_disconnect") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cloudflareIsConnected() : Promise<boolean> {
    return await TAURI_INVOKE("cloudflare_is_connected");
},
/**
 * Validates and stores a Xata API key (encrypted on-device).
 */
async xataSaveToken(token: string) : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("xata_save_token", { token }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Lists connectable Xata databases, flattened across the user's workspaces.
 */
async xataListDatabases() : Promise<Result<XataDatabase[], { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("xata_list_databases") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Mints the Postgres connection string for a Xata database/branch, embedding
 * the stored API key as the password so it never crosses to the UI.
 */
async xataBuildConnectionString(workspaceId: string, region: string, databaseName: string, branch: string | null) : Promise<Result<string, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("xata_build_connection_string", { workspaceId, region, databaseName, branch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The Xata account the stored key belongs to, so the UI can show which account
 * is currently connected.
 */
async xataAccount() : Promise<Result<XataAccount, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("xata_account") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async xataDisconnect() : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("xata_disconnect") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async xataIsConnected() : Promise<boolean> {
    return await TAURI_INVOKE("xata_is_connected");
},
/**
 * Validates and stores a PlanetScale service token (encrypted on-device).
 */
async planetscaleSaveToken(token: string) : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("planetscale_save_token", { token }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The PlanetScale organizations the stored token can access, so the UI can show
 * which account is currently connected.
 */
async planetscaleAccount() : Promise<Result<PlanetscaleOrganization[], { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("planetscale_account") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async planetscaleListDatabases(organization: string) : Promise<Result<PlanetscaleDatabase[], { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("planetscale_list_databases", { organization }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async planetscaleListBranches(organization: string, database: string, defaultBranch: string) : Promise<Result<PlanetscaleBranch[], { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("planetscale_list_branches", { organization, database, defaultBranch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Mints a fresh MySQL password on a branch (PlanetScale returns the plaintext
 * only at creation), so the connection needs no hand-copied secret.
 */
async planetscaleCreatePassword(organization: string, database: string, branch: string) : Promise<Result<PlanetscalePassword, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("planetscale_create_password", { organization, database, branch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async planetscaleDisconnect() : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("planetscale_disconnect") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async planetscaleIsConnected() : Promise<boolean> {
    return await TAURI_INVOKE("planetscale_is_connected");
},
/**
 * Validates and stores a Vercel access token (encrypted on-device).
 */
async vercelSaveToken(token: string) : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vercel_save_token", { token }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Lists connectable Vercel Postgres stores (one per project), attaching a
 * connection string when the API can read it.
 */
async vercelListStores() : Promise<Result<VercelStore[], { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vercel_list_stores") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The Vercel account the stored token belongs to, so the UI can show which
 * account is currently connected.
 */
async vercelAccount() : Promise<Result<VercelAccount, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vercel_account") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vercelDisconnect() : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vercel_disconnect") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vercelIsConnected() : Promise<boolean> {
    return await TAURI_INVOKE("vercel_is_connected");
},
async setConnectionPin(connectionId: string, pin: string | null) : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_connection_pin", { connectionId, pin }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async verifyPinAndGetCredentials(connectionId: string, pin: string) : Promise<Result<string | null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("verify_pin_and_get_credentials", { connectionId, pin }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelQuery() : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_query") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startQuery(connectionId: string, query: string) : Promise<Result<number[], { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_query", { connectionId, query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fetchQuery(queryId: number) : Promise<Result<StatementInfo, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_query", { queryId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fetchPage(queryId: number, pageIndex: number) : Promise<Result<JsonValue | null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_page", { queryId, pageIndex }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getQueryStatus(queryId: number) : Promise<Result<QueryStatus, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_query_status", { queryId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPageCount(queryId: number) : Promise<Result<number, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_page_count", { queryId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getColumns(queryId: number) : Promise<Result<JsonValue | null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_columns", { queryId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveQueryToHistory(connectionId: string, query: string, durationMs: number | null, status: string, rowCount: number, errorMessage: string | null) : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_query_to_history", { connectionId, query, durationMs, status, rowCount, errorMessage }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getQueryHistory(connectionId: string, limit: number | null) : Promise<Result<QueryHistoryEntry[], { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_query_history", { connectionId, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startLiveMonitor(connectionId: string, tableName: string, intervalMs: number, changeTypes: LiveMonitorChangeType[]) : Promise<Result<LiveMonitorSession, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_live_monitor", { connectionId, tableName, intervalMs, changeTypes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopLiveMonitor(monitorId: string) : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_live_monitor", { monitorId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getRecentQueries(connectionId: string | null, limit: number | null, statusFilter: string | null) : Promise<Result<QueryHistoryEntry[], { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_recent_queries", { connectionId, limit, statusFilter }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveScript(name: string, content: string, connectionId: string | null, description: string | null) : Promise<Result<number, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_script", { name, content, connectionId, description }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateScript(id: number, name: string, content: string, connectionId: string | null, description: string | null) : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_script", { id, name, content, connectionId, description }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getScripts(connectionId: string | null) : Promise<Result<SavedQuery[], { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_scripts", { connectionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteScript(id: number) : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_script", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSnippets(languageFilter: string | null, isSystemFilter: boolean | null, categoryFilter: string | null) : Promise<Result<SavedQuery[], { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_snippets", { languageFilter, isSystemFilter, categoryFilter }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveSnippet(name: string, content: string, language: string | null, tags: string | null, category: string | null, connectionId: string | null, description: string | null, folderId: number | null) : Promise<Result<number, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_snippet", { name, content, language, tags, category, connectionId, description, folderId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateSnippet(id: number, name: string, content: string, language: string | null, tags: string | null, category: string | null, description: string | null, folderId: number | null, connectionId: string | null) : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_snippet", { id, name, content, language, tags, category, description, folderId, connectionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteSnippet(id: number) : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_snippet", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async seedSystemSnippets() : Promise<Result<number, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("seed_system_snippets") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSnippetFolders() : Promise<Result<SnippetFolder[], { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_snippet_folders") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createSnippetFolder(name: string, parentId: number | null, color: string | null) : Promise<Result<number, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_snippet_folder", { name, parentId, color }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateSnippetFolder(id: number, name: string, color: string | null) : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_snippet_folder", { id, name, color }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteSnippetFolder(id: number) : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_snippet_folder", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveSessionState(sessionData: string) : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_session_state", { sessionData }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSessionState() : Promise<Result<string | null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_session_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSetting(key: string) : Promise<Result<string | null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_setting", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSetting(key: string, value: string) : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_setting", { key, value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async insertRow(connectionId: string, tableName: string, schemaName: string | null, rowData: Partial<{ [key in string]: JsonValue }>) : Promise<Result<MutationResult, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("insert_row", { connectionId, tableName, schemaName, rowData }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateCell(connectionId: string, tableName: string, schemaName: string | null, primaryKeyColumn: string, primaryKeyValue: JsonValue, columnName: string, newValue: JsonValue) : Promise<Result<MutationResult, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_cell", { connectionId, tableName, schemaName, primaryKeyColumn, primaryKeyValue, columnName, newValue }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getBlobBytes(connectionId: string, tableName: string, schemaName: string | null, primaryKeyColumn: string, primaryKeyValue: JsonValue, columnName: string) : Promise<Result<number[], { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_blob_bytes", { connectionId, tableName, schemaName, primaryKeyColumn, primaryKeyValue, columnName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteRows(connectionId: string, tableName: string, schemaName: string | null, primaryKeyColumn: string, primaryKeyValues: JsonValue[]) : Promise<Result<MutationResult, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_rows", { connectionId, tableName, schemaName, primaryKeyColumn, primaryKeyValues }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async duplicateRow(connectionId: string, tableName: string, schemaName: string | null, primaryKeyColumn: string, primaryKeyValue: JsonValue) : Promise<Result<MutationResult, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("duplicate_row", { connectionId, tableName, schemaName, primaryKeyColumn, primaryKeyValue }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportTable(connectionId: string, tableName: string, schemaName: string | null, format: ExportFormat, limit: number | null, whereClause: string | null, orderBy: string | null) : Promise<Result<string, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_table", { connectionId, tableName, schemaName, format, limit, whereClause, orderBy }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async softDeleteRows(connectionId: string, tableName: string, schemaName: string | null, primaryKeyColumn: string, primaryKeyValues: JsonValue[], softDeleteColumn: string | null) : Promise<Result<SoftDeleteResult, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("soft_delete_rows", { connectionId, tableName, schemaName, primaryKeyColumn, primaryKeyValues, softDeleteColumn }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async undoSoftDelete(connectionId: string, tableName: string, schemaName: string | null, primaryKeyColumn: string, primaryKeyValues: JsonValue[], softDeleteColumn: string) : Promise<Result<MutationResult, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("undo_soft_delete", { connectionId, tableName, schemaName, primaryKeyColumn, primaryKeyValues, softDeleteColumn }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async truncateTable(connectionId: string, tableName: string, schemaName: string | null, cascade: boolean | null) : Promise<Result<TruncateResult, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("truncate_table", { connectionId, tableName, schemaName, cascade }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async truncateDatabase(connectionId: string, schemaName: string | null, confirm: boolean) : Promise<Result<TruncateResult, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("truncate_database", { connectionId, schemaName, confirm }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dumpDatabase(connectionId: string, outputPath: string) : Promise<Result<DumpResult, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dump_database", { connectionId, outputPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async executeBatch(connectionId: string, statements: string[]) : Promise<Result<MutationResult, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("execute_batch", { connectionId, statements }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDatabaseSchema(connectionId: string) : Promise<Result<DatabaseSchema, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_database_schema", { connectionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDatabaseMetadata(connectionId: string) : Promise<Result<DatabaseMetadata, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_database_metadata", { connectionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async seedTable(connectionId: string, tableName: string, schemaName: string | null, count: number) : Promise<Result<SeedResult, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("seed_table", { connectionId, tableName, schemaName, count }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async parseSql(sql: string) : Promise<Result<JsonValue, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("parse_sql", { sql }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async buildSql(ast: JsonValue) : Promise<Result<string, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("build_sql", { ast }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Export database schema to SQL DDL format.
 */
async exportSchemaSql(connectionId: string, dialect: string) : Promise<Result<string, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_schema_sql", { connectionId, dialect }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Export database schema to Drizzle ORM TypeScript format.
 */
async exportSchemaDrizzle(connectionId: string, dialect: string) : Promise<Result<string, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_schema_drizzle", { connectionId, dialect }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aiComplete(prompt: string, connectionId: string | null, maxTokens: number | null) : Promise<Result<AIResponse, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_complete", { prompt, connectionId, maxTokens }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aiCompleteStream(requestId: string, prompt: string, connectionId: string | null, maxTokens: number | null, promptMode: string | null, onEvent: TAURI_CHANNEL<AiStreamEvent>) : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_complete_stream", { requestId, prompt, connectionId, maxTokens, promptMode, onEvent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aiSetProvider(provider: string) : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_set_provider", { provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aiGetProvider() : Promise<Result<string, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_get_provider") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aiGetConfig() : Promise<Result<AiServiceConfig, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_get_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aiSetConfig(config: AiServiceConfig) : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_set_config", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aiGetStatus() : Promise<Result<AiStatus, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_get_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aiListProviderModels(provider: string) : Promise<Result<AiModelOption[], { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_list_provider_models", { provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aiGetUsageSummary(limit: number | null) : Promise<Result<AiUsageSummary, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_get_usage_summary", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aiSetGeminiKey(apiKey: string) : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_set_gemini_key", { apiKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aiConfigureOllama(endpoint: string | null, model: string | null) : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_configure_ollama", { endpoint, model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aiGetOllamaStatus() : Promise<Result<OllamaStatus, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_get_ollama_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aiListOllamaCatalog() : Promise<Result<OllamaCatalogEntry[], { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_list_ollama_catalog") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aiPullOllamaModel(requestId: string, model: string, onEvent: TAURI_CHANNEL<OllamaPullEvent>) : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_pull_ollama_model", { requestId, model, onEvent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aiCancelOllamaPull(requestId: string) : Promise<Result<boolean, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_cancel_ollama_pull", { requestId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aiDeleteOllamaModel(model: string) : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_delete_ollama_model", { model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aiListOllamaModels() : Promise<Result<string[], { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_list_ollama_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aiInstallOllama(requestId: string, onEvent: TAURI_CHANNEL<OllamaInstallEvent>) : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_install_ollama", { requestId, onEvent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aiCancelOllamaInstall(requestId: string) : Promise<Result<boolean, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_cancel_ollama_install", { requestId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aiStartOllama() : Promise<Result<OllamaStatus, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_start_ollama") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check whether Groq provider is usable (env or DB keys present).
 * Returns key count detected. Never exposes the key values.
 */
async aiGroqStatus() : Promise<Result<GroqStatus, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_groq_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aiAbortStream(requestId: string) : Promise<Result<boolean, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_abort_stream", { requestId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aiKeysList(provider: string) : Promise<Result<AiApiKeyRecord[], { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_keys_list", { provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aiKeysAdd(provider: string, label: string, apiKey: string) : Promise<Result<number, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_keys_add", { provider, label, apiKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aiKeysDelete(id: number) : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_keys_delete", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aiKeysSetActive(id: number, active: boolean) : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_keys_set_active", { id, active }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aiKeysTest(id: number, model: string | null, prompt: string | null) : Promise<Result<AiKeyTestResult, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_keys_test", { id, model, prompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Test the configured provider key source (environment keys plus active saved keys).
 */
async aiKeysTestProvider(provider: string, model: string | null, prompt: string | null) : Promise<Result<AiKeyTestResult, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_keys_test_provider", { provider, model, prompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Test an unsaved key (used by the "Test before save" button).
 */
async aiKeysTestRaw(provider: string, apiKey: string, model: string | null, prompt: string | null) : Promise<Result<AiKeyTestResult, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_keys_test_raw", { provider, apiKey, model, prompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listDatabases() : Promise<Result<RegisteredDatabase[], { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_databases") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getActiveStoragePath() : Promise<Result<string, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_active_storage_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async switchStorage(name: string) : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("switch_storage", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async registerDatabase(name: string, path: string) : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("register_database", { name, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createDatabase(name: string, path: string) : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_database", { name, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetStorage() : Promise<Result<null, { kind: string; detail: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_storage") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCredentialStorageStatus() : Promise<CredentialStorageStatus> {
    return await TAURI_INVOKE("get_credential_storage_status");
},
async getKeyringInstallPlan() : Promise<KeyringInstallPlan | null> {
    return await TAURI_INVOKE("get_keyring_install_plan");
},
async installCredentialKeyring() : Promise<KeyringInstallResult> {
    return await TAURI_INVOKE("install_credential_keyring");
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AIResponse = { content: string; suggested_queries: string[] | null; tokens_used: number | null; provider: string }
export type AiApiKeyRecord = { id: number; provider: string; label: string; is_active: boolean; last_tested: number | null; last_status: string | null; created_at: number; updated_at: number }
export type AiKeyTestResult = { ok: boolean; message: string }
export type AiModelOption = { id: string; label: string; tier: string }
export type AiProviderReadiness = { provider: string; ready: boolean; detail: string | null; key_count: number | null }
export type AiServiceConfig = { provider: string; model: string; ollama_endpoint: string }
export type AiStatus = { active_provider: string; active_model: string; ready: boolean; providers: AiProviderReadiness[] }
export type AiStreamEvent = { type: "token"; text: string } | { type: "final"; content: string } | { type: "error"; message: string }
export type AiUsageEntry = { id: number; provider: string; model: string; source: string; input_tokens: number | null; output_tokens: number | null; total_tokens: number | null; estimated_cost_usd: number | null; estimated: boolean; created_at: number }
export type AiUsageProviderSummary = { provider: string; request_count: number; input_tokens: number; output_tokens: number; total_tokens: number; estimated_cost_usd: number }
export type AiUsageSummary = { total_requests: number; input_tokens: number; output_tokens: number; total_tokens: number; estimated_cost_usd: number; providers: AiUsageProviderSummary[]; recent: AiUsageEntry[] }
export type ColumnInfo = { name: string; data_type: string; is_nullable: boolean; default_value: string | null; 
/**
 * Whether this column is part of the primary key
 */
is_primary_key?: boolean; 
/**
 * Whether this column auto-increments (SERIAL, AUTOINCREMENT, etc.)
 */
is_auto_increment?: boolean; 
/**
 * Foreign key relationship, if any
 */
foreign_key?: ForeignKeyInfo | null }
export type ConnectionHistoryEntry = { id: number; connection_id: string; connection_name: string; database_type: string; attempted_at: number; success: boolean; error_message: string | null; duration_ms: number | null }
export type ConnectionInfo = { id: string; name: string; connected: boolean; database_type: DatabaseInfo; last_connected_at: number | null; created_at: number | null; updated_at: number | null; pin_hash: string | null; favorite: boolean | null; color: string | null; sort_order: number | null }
export type CredentialStorageBackend = "os_keyring" | "local_encrypted_file"
export type CredentialStorageStatus = { backend: CredentialStorageBackend; message: string; storage_path: string | null; install_hint: string | null }
export type DataFileSourceEntry = { path: string; viewName: string; fileType: string; status: DataFileSourceStatus; error: string | null }
export type DataFileSourceStatus = "active" | "missing" | "failed"
export type DatabaseConnectResult = { connected: boolean; fileSources: DataFileSourceEntry[] | null }
export type DatabaseFileKind = "sqlite" | "duckdb" | "unknown"
export type DatabaseInfo = { Postgres: { connection_string: string; ssh_config: SshConfig | null } } | { CockroachDB: { connection_string: string; ssh_config: SshConfig | null } } | { MySQL: { connection_string: string; ssh_config: SshConfig | null } } | { MariaDB: { connection_string: string; ssh_config: SshConfig | null } } | { SQLite: { db_path: string } } | 
/**
 * DuckDB database file (embedded, like SQLite).
 * 
 * When `file_sources` is non-empty the connection is opened in-memory
 * (`db_path` is `:memory:`) and each source file is registered as a
 * read-only view — this is the "query a CSV/Parquet/JSON file" mode.
 */
{ DuckDB: { db_path: string; file_sources?: string[] } } | 
/**
 * LibSQL/Turso database - can be local path or remote URL with auth token
 */
{ LibSQL: { 
/**
 * Either a local file path or remote URL (libsql://...)
 */
url: string; 
/**
 * Auth token for remote connections (optional for local)
 */
auth_token: string | null } }
/**
 * Database-level metadata information
 */
export type DatabaseMetadata = { 
/**
 * Total size of the database in bytes
 */
size_bytes: number; 
/**
 * Database creation timestamp (if available)
 */
created_at: number | null; 
/**
 * Last modification timestamp (if available)
 */
last_updated: number | null; 
/**
 * Total number of rows across all tables
 */
row_count_total: number; 
/**
 * Number of tables in the database
 */
table_count: number; 
/**
 * Database host or file path
 */
host: string; 
/**
 * Database name
 */
database_name: string | null }
export type DatabaseSchema = { tables: TableInfo[]; schemas: string[]; unique_columns: string[] }
/**
 * Result of a database dump operation
 */
export type DumpResult = { success: boolean; file_path: string; size_bytes: number; tables_dumped: number; rows_dumped: number; message: string | null }
/**
 * Export format options
 */
export type ExportFormat = "json" | "sql_insert" | "csv"
export type FailedDuckDbImport = { path: string; fileType: string; error: string }
/**
 * Information about a foreign key relationship
 */
export type ForeignKeyInfo = { 
/**
 * The table that this foreign key references
 */
referenced_table: string; 
/**
 * The column in the referenced table
 */
referenced_column: string; 
/**
 * The schema of the referenced table (empty for SQLite)
 */
referenced_schema: string }
export type GroqStatus = { available: boolean; key_count: number }
export type ImportFilesIntoDuckDbResult = { tables: ImportedDuckDbTable[]; failed: FailedDuckDbImport[]; warnings: string[] }
export type ImportedDuckDbTable = { name: string; sourcePath: string; fileType: string; rowCount: number | null }
export type IndexInfo = { name: string; column_names: string[]; is_unique: boolean; is_primary: boolean }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
/**
 * How the OS-backed credential store can be installed on this machine.
 */
export type KeyringInstallPlan = { 
/**
 * Detected package manager (e.g. "pacman", "apt-get", "dnf"), if any.
 */
package_manager: string | null; 
/**
 * Package that provides the OS Secret Service (e.g. "gnome-keyring").
 */
package: string; 
/**
 * Human-readable command the user could run themselves.
 */
command: string; 
/**
 * True when Dora can run the install itself (via pkexec on Linux).
 */
can_auto_install: boolean }
export type KeyringInstallResult = { ok: boolean; message: string }
export type LiveMonitorChangeType = "insert" | "update" | "delete"
export type LiveMonitorSession = { monitorId: string; eventName: string }
/**
 * Result of a mutation operation
 */
export type MutationResult = { success: boolean; affected_rows: number; message: string | null }
export type OllamaCatalogEntry = { name: string; label: string; description: string; installed: boolean; size_bytes: number | null }
export type OllamaInstallEvent = { type: "status"; message: string } | { type: "progress"; completed: number; total: number | null; percent: number } | { type: "done"; version: string | null; install_path: string } | { type: "error"; message: string }
export type OllamaPullEvent = { type: "status"; message: string } | { type: "progress"; completed: number; total: number; percent: number; eta_seconds: number | null } | { type: "done"; model: string } | { type: "error"; message: string }
export type OllamaStatus = { running: boolean; endpoint: string; version: string | null; installed_count: number; managed: boolean; install_path: string | null; binary_ready: boolean }
export type QueryHistoryEntry = { id: number; connection_id: string; query_text: string; executed_at: number; duration_ms: number | null; status: string; row_count: number; error_message: string | null }
export type QueryStatus = "Pending" | "Running" | "Completed" | "Error"
export type RegisteredDatabase = { name: string; path: string; active: boolean }
export type SaveDataFileSessionResult = { path: string; tables: SavedDataFileTable[]; skipped: SkippedDataFileSource[]; warnings: string[] }
export type SavedDataFileTable = { name: string; sourcePath: string; rowCount: number | null }
export type SavedQuery = { id: number; name: string; description: string | null; query_text: string; connection_id: string | null; tags: string | null; category: string | null; created_at: number; updated_at: number; favorite: boolean; is_snippet: boolean; is_system: boolean; language: string | null; folder_id: number | null }
export type SeedResult = { rows_inserted: number; table: string }
export type SkippedDataFileSource = { path: string; viewName: string; status: DataFileSourceStatus; error: string | null }
export type SnippetFolder = { id: number; name: string; parent_id: number | null; color: string | null; created_at: number; updated_at: number }
/**
 * Result of a soft delete operation
 */
export type SoftDeleteResult = { success: boolean; affected_rows: number; message: string | null; 
/**
 * Unix timestamp when deletion happened (for undo window)
 */
deleted_at: number; 
/**
 * How many seconds the undo window lasts
 */
undo_window_seconds: number }
export type SshConfig = { host: string; port: number; username: string; private_key_path: string | null; password: string | null }
export type SupabaseProject = { id: string; name: string; region: string; status: string; dbHost: string; dbVersion: string }
export type SupabaseOrganization = { id: string; name: string }
export type TursoDatabase = { name: string; hostname: string; organizationSlug: string; group: string; primaryRegion: string }
export type TursoOrganization = { slug: string; name?: string }
export type CloudflareAccount = { id: string; name?: string }
export type CloudflareD1Database = { accountId: string; uuid: string; name: string }
export type NeonAccount = { email?: string; name?: string }
export type NeonBranch = { id: string; name: string; isDefault: boolean }
export type NeonDatabase = { projectId: string; projectName: string; branchId: string; databaseName: string; roleName: string }
export type XataAccount = { email?: string; fullname?: string }
/**
 * A selectable Xata database, flattened across the user's workspaces. The
 * workspace id (PG user) and region (PG host) are carried so we can assemble a
 * Postgres connection string for it later without re-discovering anything. The
 * branch defaults to `main` at connect time.
 */
export type XataDatabase = { workspaceId: string; workspaceName: string; databaseName: string; region: string;
/**
 * Whether Xata reports this database as reachable over the Postgres
 * protocol. Databases without it can't be connected as a Postgres source,
 * so the connect-flow can flag them.
 */
postgresEnabled: boolean }
/**
 * A branch of a PlanetScale database. `is_default` marks the database's default
 * branch (the one to preselect). This is the branch-aware hook other plans
 * (05-branch-aware-connects) build on.
 */
export type PlanetscaleBranch = { name: string; production: boolean; isDefault: boolean }
/**
 * A selectable PlanetScale database. `default_branch` is carried so the
 * connect-flow can preselect the primary branch without re-discovering it.
 */
export type PlanetscaleDatabase = { name: string; defaultBranch: string }
/**
 * The PlanetScale organization the stored token belongs to, shown in the UI so
 * the user can confirm which account is connected.
 */
export type PlanetscaleOrganization = { name: string }
/**
 * A freshly minted MySQL credential for a branch. PlanetScale only returns the
 * plaintext password once (at creation), so the connect-flow uses this
 * immediately to assemble a connection string — the user never copies a secret.
 */
export type PlanetscalePassword = { username: string; host: string; password: string }
export type VercelAccount = { username?: string; email?: string; name?: string }
/**
 * A selectable Vercel Postgres "store" (one per project that has a Postgres
 * connection string in its environment). `connection_string` is `None` when the
 * value couldn't be read (e.g. the env var is marked `sensitive`), in which case
 * the connect-flow asks the user to paste the `POSTGRES_URL` instead.
 */
export type VercelStore = { projectId: string; projectName: string;
/**
 * The env key the connection string came from (e.g. `POSTGRES_URL`), shown
 * in the picker so the user knows which credential they're connecting with.
 */
envKey?: string | null;
/**
 * The decrypted connection string, when the API returned a readable value.
 */
connectionString?: string | null }
export type StatementInfo = { returns_values: boolean; status: QueryStatus; first_page: JsonValue; affected_rows: number | null; page_count: number; rows_received: number; error: string | null }
export type TAURI_CHANNEL<TSend> = null
export type TableInfo = { name: string; schema: string; columns: ColumnInfo[]; 
/**
 * Names of columns that form the primary key (supports composite keys)
 */
primary_key_columns?: string[]; 
/**
 * List of indexes on this table
 */
indexes?: IndexInfo[]; 
/**
 * Estimated row count (may be approximate for performance)
 */
row_count_estimate?: number | null }
/**
 * Result of a truncate operation
 */
export type TruncateResult = { success: boolean; affected_rows: number; tables_truncated: string[]; message: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
