import type { ProductCategoryRecord } from "../types"

export function generateProductCategories(): ProductCategoryRecord[] {
  return [
    {
      id: 1,
      name: "Electronics",
      slug: "electronics",
      description: "Electronic devices and accessories",
      parentId: null,
      isActive: true,
      displayOrder: 1,
    },
    {
      id: 2,
      name: "Computers",
      slug: "computers",
      description: "Desktop and laptop computers",
      parentId: 1,
      isActive: true,
      displayOrder: 1,
    },
    {
      id: 3,
      name: "Mobile Devices",
      slug: "mobile-devices",
      description: "Smartphones and tablets",
      parentId: 1,
      isActive: true,
      displayOrder: 2,
    },
    {
      id: 4,
      name: "Home & Garden",
      slug: "home-garden",
      description: "Home improvement and garden supplies",
      parentId: null,
      isActive: true,
      displayOrder: 2,
    },
    {
      id: 5,
      name: "Furniture",
      slug: "furniture",
      description: "Indoor and outdoor furniture",
      parentId: 4,
      isActive: true,
      displayOrder: 1,
    },
    {
      id: 6,
      name: "Clothing",
      slug: "clothing",
      description: "Apparel and fashion items",
      parentId: null,
      isActive: true,
      displayOrder: 3,
    },
    {
      id: 7,
      name: "Men's Clothing",
      slug: "mens-clothing",
      description: "Clothing for men",
      parentId: 6,
      isActive: true,
      displayOrder: 1,
    },
    {
      id: 8,
      name: "Women's Clothing",
      slug: "womens-clothing",
      description: "Clothing for women",
      parentId: 6,
      isActive: true,
      displayOrder: 2,
    },
    {
      id: 9,
      name: "Books",
      slug: "books",
      description: "Physical and digital books",
      parentId: null,
      isActive: true,
      displayOrder: 4,
    },
    {
      id: 10,
      name: "Sports & Outdoors",
      slug: "sports-outdoors",
      description: "Sports equipment and outdoor gear",
      parentId: null,
      isActive: true,
      displayOrder: 5,
    },
    {
      id: 11,
      name: "Archived Category",
      slug: "archived",
      description: "No longer in use",
      parentId: null,
      isActive: false,
      displayOrder: 99,
    },
    {
      id: 12,
      name: "Gaming",
      slug: "gaming",
      description: "Video games and gaming accessories",
      parentId: 1,
      isActive: true,
      displayOrder: 3,
    },
  ]
}
