export { default as AppView } from './app-view'
export { default as ChangelogView } from './changelog-view'
export { default as DocsView } from './docs-view'
export { default as DownloadsView } from './downloads-view'
export { default as HomeView } from './home-view'
export { default as NotFound } from './not-found-view'
export { default as PrivacyView } from './privacy-view'
