// Generated by scripts/sync-changelog-data.ts — do not edit manually.
// Regenerate with: bun run generate:changelog-data

export type ChangelogReleaseGroup = {
	name: string
	items: string[]
}

export type ChangelogRelease = {
	version: string
	date: string
	tagUrl: string
	groups: ChangelogReleaseGroup[]
}

export const CURRENT_VERSION = "0.36.0"

export const CHANGELOG_RELEASES: ChangelogRelease[] = [
	{
		version: "0.31.0",
		date: "2026-07-04",
		tagUrl: "https://github.com/remcostoeten/dora/releases/tag/v0.31.0",
		groups: [
			{
				name: "Build",
				items: [
				"build(winget): use standalone wingetcreate.exe (Appx unsupported on PS7)",
				"build(winget): submit generated manifests instead of wingetcreate update",
				]
			},
			{
				name: "Chores",
				items: [
				"chore(aur): update dora to 0.30.3",
				]
			},
			{
				name: "Features",
				items: [
				"feat(cli): add dora cli with various args for tests, deployment and debug (#184) (#184)",
				"feat: add Ctrl+Q shortcut to quit application",
				"feat(posthog): HogQL connector, built-in analytics dashboard, and browsing fixes",
				"feat(marketing): promote PostHog and rework the multi-connection showcase",
				]
			}
		]
	},
	{
		version: "0.32.0",
		date: "2026-07-08",
		tagUrl: "https://github.com/remcostoeten/dora/releases/tag/v0.32.0",
		groups: [
			{
				name: "Bug Fixes",
				items: [
				"fix(studio): fetch all result pages instead of only the first 50 rows",
				"fix(backend): issue a real cancel request for Postgres/CockroachDB queries",
				]
			},
			{
				name: "Chores",
				items: [
				"chore(aur): update dora to 0.31.0",
				"chore: docs polish, PostHog showcase, ORM cockpit link fixes, studio toolbar/ai-keys fixes (#186) (#186)",
				]
			}
		]
	},
	{
		version: "0.33.0",
		date: "2026-07-11",
		tagUrl: "https://github.com/remcostoeten/dora/releases/tag/v0.33.0",
		groups: [
			{
				name: "Bug Fixes",
				items: [
				"fix(release): ship arm64-only Homebrew cask, add tap docs",
				"fix(studio): keep the connection dropdown open across repeated deletes",
				"fix(backend): give every query a unique id so concurrent submissions don't clobber each other",
				]
			},
			{
				name: "Chores",
				items: [
				"chore(aur): update dora to 0.32.0",
				"chore(marketing): drop the postbuild SEO audit",
				]
			},
			{
				name: "Features",
				items: [
				"feat(marketing): instrument PostHog and show live HogQL stats",
				"feat(studio): build out the PostHog analytics dashboard",
				"feat(studio): infer column types for metadata-less query results",
				"feat: PostHog analytics dashboard, typed ad-hoc results, single-hue brand palette (#187) (#187)",
				]
			},
			{
				name: "Refactoring",
				items: [
				"refactor(studio): extract command palette internals, move palette to Ctrl+K",
				"refactor(marketing): derive the whole palette from one brand hue",
				]
			}
		]
	},
	{
		version: "0.34.0",
		date: "2026-07-15",
		tagUrl: "https://github.com/remcostoeten/dora/releases/tag/v0.34.0",
		groups: [
			{
				name: "Bug Fixes",
				items: [
				"fix(docs): remove duplicate H1 from doc bodies",
				]
			},
			{
				name: "Chores",
				items: [
				"chore(aur): update dora to 0.33.0",
				]
			},
			{
				name: "Documentation",
				items: [
				"docs(installation): document Winget and APT install channels",
				]
			},
			{
				name: "Features",
				items: [
				"feat: refresh Dora promo and analytics",
				]
			}
		]
	},
	{
		version: "0.35.0",
		date: "2026-07-17",
		tagUrl: "https://github.com/remcostoeten/dora/releases/tag/v0.35.0",
		groups: [
			{
				name: "Chores",
				items: [
				"chore(aur): update dora to 0.34.0",
				]
			},
			{
				name: "Performance",
				items: [
				"perf(studio): cut re-renders, virtualize result tables, defer startup bundle (#188) (#188)",
				]
			}
		]
	},
	{
		version: "0.35.1",
		date: "2026-07-17",
		tagUrl: "https://github.com/remcostoeten/dora/releases/tag/v0.35.1",
		groups: [
			{
				name: "Chores",
				items: [
				"chore(aur): update dora to 0.35.0",
				]
			},
			{
				name: "Documentation",
				items: [
				"docs(readme): lead with compressed demo tour, tighten intro",
				]
			}
		]
	},
	{
		version: "0.36.0",
		date: "2026-07-20",
		tagUrl: "https://github.com/remcostoeten/dora/releases/tag/v0.36.0",
		groups: [
			{
				name: "Chores",
				items: [
				"chore(aur): update dora to 0.35.1",
				"chore(deps): upgrade @remcostoeten/analytics to 1.7.0 (#189) (#189)",
				]
			},
			{
				name: "Documentation",
				items: [
				"docs(readme): new hero clip (browse → edit cell → run SQL), drop stale hero.webp",
				"docs(readme): refresh header + hero clip with command palette",
				]
			}
		]
	},
	{
		version: "0.30.3",
		date: "2026-06-29",
		tagUrl: "https://github.com/remcostoeten/dora/releases/tag/v0.30.3",
		groups: [
			{
				name: "Features",
				items: [
				"DuckDB-backed local file queries (CSV, Parquet, JSON) now run in a separate helper process instead of being linked into the main app binary, keeping the heavy engine out of the core download",
				]
			},
			{
				name: "Bug Fixes",
				items: [
				"the SQL and ORM editors now load reliably in packaged builds — Monaco and its fonts are fully self-hosted instead of being fetched from a CDN that the app's content-security policy blocked, which previously left the editor stuck on a blank loading state with mis-spaced text in release builds",
				"connection-refused errors now name the host that could not be reached instead of showing a generic message",
				]
			},
			{
				name: "Performance",
				items: [
				"data-viewer edits now apply instantly — optimistic updates no longer flash back to the stale value before the save lands",
				]
			},
			{
				name: "Styling",
				items: [
				"a single 12-blade radial spinner is now used everywhere a loading indicator appears",
				]
			}
		]
	},
	{
		version: "0.30.2",
		date: "2026-06-29",
		tagUrl: "https://github.com/remcostoeten/dora/releases/tag/v0.30.2",
		groups: [
			{
				name: "Features",
				items: [
				"Privacy mode can now mask cell values in database results, including grids, SQL results, and runner output (#182)",
				]
			},
			{
				name: "Bug Fixes",
				items: [
				"Debian/Ubuntu install instructions and apt repository generation now use the current GitHub Pages path",
				]
			},
			{
				name: "Chores",
				items: [
				"Updated the Tauri updater plugin to 2.10.1",
				"Changelog data generation now skips the empty Unreleased placeholder",
				]
			}
		]
	},
	{
		version: "0.30.1",
		date: "2026-06-27",
		tagUrl: "https://github.com/remcostoeten/dora/releases/tag/v0.30.1",
		groups: [
			{
				name: "Bug Fixes",
				items: [
				"fix(studio): UI quick wins — remove AI index button, lower AI panel, unified spinner (#181) (#181)",
				"fix(studio): pin Monaco loader to bundled core so editor loads in release builds",
				]
			},
			{
				name: "Chores",
				items: [
				"chore(aur): update dora to 0.30.0",
				]
			},
			{
				name: "Features",
				items: [
				"feat(drizzle-runner): align translator with LSP, add $count, fix Prisma toolbar (#179) (#179)",
				"feat(prisma-runner): style schema viewer + add syntax-highlighted schema.prisma preview (#180) (#180)",
				]
			}
		]
	},
	{
		version: "0.30.0",
		date: "2026-06-21",
		tagUrl: "https://github.com/remcostoeten/dora/releases/tag/v0.30.0",
		groups: [
			{
				name: "Features",
				items: [
				"spin up a local MySQL container straight from the Docker manager — MySQL joins PostgreSQL, MariaDB, and CockroachDB as a one-click provisionable engine, with version presets, auto-detected free port, connect-in-data-viewer, SQL seeding, and Compose export",
				"the bundled `docker-compose.databases.yml` now covers every server engine Dora can talk to locally — PostgreSQL, MySQL, MariaDB, CockroachDB, and libSQL/sqld — for testing against a real database in one `docker compose up`",
				"ORM cockpit — link a project folder, detect its Drizzle or Prisma schema, compare it against the live database, and preview a dialect-correct migration; drift is grouped per table and flagged safe/review/destructive, with destructive and review statements gated behind explicit opt-in before the SQL is handed to the console",
				"connect a Cloudflare D1 database with an API token and pick it from your account — a native HTTP query engine, no local file required (#139, #150)",
				"connect a PlanetScale database with a service token and pick a branch (#141, #149)",
				"connect a Vercel Postgres store with a token and pick it from your account (#147)",
				"connect a Xata database with a key and pick it from your account (#140, #148)",
				"Neon connections are now branch-aware — pick a branch when a project has more than one (#142, #156)",
				"keep multiple database connections open at once, each with its own isolated tab group; a connection tab bar above the table tabs switches between them (with status dots and per-connection close), and switching preserves each connection's open tabs, active tab, filters and scroll state. Cycle connections with `Ctrl+Shift+[` / `Ctrl+Shift+]` (#96)",
				"hardened Turso, Supabase, and Neon connect flows with account visibility — Turso gains robust CLI detection and in-app sign-in, and each provider shows \"Connected as\", a refresh button, paginated project/organization lists, and clearer empty and error states",
				]
			},
			{
				name: "Bug Fixes",
				items: [
				"AI provider errors now use clear, consistent copy across all providers (Groq, OpenAI, Anthropic, Gemini, Ollama): rate limits, invalid keys, missing models, and an offline Ollama daemon each surface an actionable message instead of a raw HTTP status and response body (#82)",
				"the AI rate-limit message includes a retry hint so the user knows to wait and try again (#82)",
				"data-grid optimistic cell edits no longer flash back to the stale value before the save lands",
				"the sidebar no longer blanks out when you rename, duplicate, or drop a table",
				]
			},
			{
				name: "Performance",
				items: [
				"the marketing home page ships ~24.7 kB less gzipped JS on first load (-8.6%) by deferring the animation engine until after hydration; first paint is pure CSS so there is no perceived change",
				]
			},
			{
				name: "Documentation",
				items: [
				"AI Keys settings now spell out that Groq/OpenAI/Anthropic/Gemini need an API key while Ollama runs locally with no key, pointing to `docs/ai-providers.md` for setup (#82)",
				"new end-user installation guide with a full platform matrix (macOS Apple Silicon/Intel, Windows, Linux packages, and the AUR)",
				"new connection guides for Cloudflare D1 and Xata, plus ORM Cockpit and ORM Runners guides on doradb.app/docs",
				]
			},
			{
				name: "Closed issues",
				items: [
				"ORM & migration cockpit (Pillar 2) — tracking #143, Wave A schema IR + introspection #144, Wave B parsers + folder linking + diff engine #145, Wave C/D migration generation + cockpit UI #146",
				"Cloudflare D1 connector #139",
				"Xata connector #140",
				"PlanetScale connector #141",
				"Branch-aware connects for PlanetScale and Neon #142",
				"Documentation — docs site at doradb.app/docs #130, installation & distribution matrix #131, provider & dialect reference #132, serverless & hosted provider showcase #133, full feature showcase #134",
				]
			}
		]
	},
	{
		version: "0.29.0",
		date: "2026-06-15",
		tagUrl: "https://github.com/remcostoeten/dora/releases/tag/v0.29.0",
		groups: [
			{
				name: "Bug Fixes",
				items: [
				"fix(backend): replace high-risk unwrap/panic with error propagation",
				"fix(studio): resolve strictNullChecks violations",
				]
			},
			{
				name: "CI/CD",
				items: [
				"ci: lower asset count floor to 9 after dropping Intel-macOS build",
				"ci: bump bun pin to 1.3.14 and add tsc --noEmit typecheck gate",
				]
			},
			{
				name: "Chores",
				items: [
				"chore(ts): enable strictNullChecks for studio and desktop",
				]
			},
			{
				name: "Features",
				items: [
				"feat(marketing): add 15 hosted-provider connection guides for SEO",
				"feat(connections): Fly.io proxy hint in connection dialog",
				"feat(connections): first-class presets for 10 hosted providers",
				"feat(prisma-runner): Prisma ORM Runner — write & execute Prisma client queries natively (#137)",
				"feat(connections): hosted/serverless provider support + Supabase integration (#128)",
				"feat(connections): one-click Supabase OAuth + reliable pooler host",
				"feat(marketing): feature-showcase polish + Prisma runner showcase",
				"feat(studio): connection dialog, docker view & Supabase flow refinements",
				"feat(database-studio): drop column support",
				]
			}
		]
	},
	{
		version: "0.28.0",
		date: "2026-06-14",
		tagUrl: "https://github.com/remcostoeten/dora/releases/tag/v0.28.0",
		groups: [
			{
				name: "Features",
				items: [
				"add source metadata layer (`describeConnectionSource`, `getSourceCaps`, `isUiActionVisible`) so UI visibility follows connection capabilities instead of engine string checks",
				"open CSV, JSON, Parquet, TSV, and NDJSON as readonly **data files** (DuckDB-backed sessions) with health indicators, recovery actions, and connection summaries",
				"**Save as DuckDB** — materialize active data-file sessions into editable `.duckdb` files",
				"**Import files** — import CSV/JSON/Parquet as physical tables in native DuckDB file connections",
				"open SQLite and DuckDB files as editable embedded databases",
				"drag tabs to reorder them (pinned tabs stay grouped first) (#105)",
				"open tabs are persisted and restored across relaunch (#98)",
				"binary/blob cells now show inline hex for small values and a `<type — size>` summary (with magic-byte detection) for large ones, instead of a bare byte count (#90)",
				"data-grid filters can be joined with OR via an AND/OR toggle, not only AND (#102)",
				"JSON/CSV/SQL export now respects the active filters and sort order instead of dumping the whole table or just the loaded page (#99)",
				"back up a database to a `.sql` dump and restore from one via the data-grid actions menu (#103)",
				"\"Fix with AI\" on a failed query sends the query and error to the AI assistant (#104)",
				]
			},
			{
				name: "Reliability",
				items: [
				"recover gracefully from missing or moved data-file sources when reopening a connection",
				"clearer failure copy for save/import paths (no active files, destination conflicts, partial imports, schema refresh warnings)",
				]
			},
			{
				name: "Fixes",
				items: [
				"schema-visualizer SVG and PNG export now follows the active theme instead of always exporting dark-theme colours (#112)",
				"cancelling a Postgres query no longer logs benign \"channel closed\" error noise (#83)",
				"SQL console loading shell and editor surfaces now use a themed `--editor` token, so they no longer render a black rectangle in light and non-dark themes (#114)",
				"data-grid column headers show a tooltip with the full column name and type, but only when the label is actually truncated (#115)",
				"database-studio empty states no longer re-fire their entrance animation on every tab switch, removing the zoom/flicker (#113)",
				"AI provider status dot is no longer colour-only — it uses a filled vs hollow shape plus `aria-pressed`/`aria-label` for screen readers (#116)",
				"SQLite `VACUUM`, `DETACH DATABASE`, and some `PRAGMA` forms no longer fail to run — they are classified via a keyword fallback when the AST parser rejects them (#94)",
				]
			},
			{
				name: "Documentation",
				items: [
				"README support matrix and **Local files** section explaining database files vs data files",
				"add `docs/ai-providers.md` — per-provider setup, recommended models, key storage, and troubleshooting (#91)",
				]
			},
			{
				name: "Tooling",
				items: [
				"new `dora-runner` CLI replacing the legacy `dora-cli`/`dora-manager-executor` (#86)",
				"migrate CI workflows to Blacksmith runners (#87)",
				]
			},
			{
				name: "Internal",
				items: [
				"remove unused `DisabledFeature`/`NotImplemented` components and the deprecated `database-studio/api.ts` (#95)",
				"drop the inaccurate PgBouncer scaffold comment in `types.rs` now that `use_simple_query` is fully wired (#92)",
				"model statement execution result as an enum instead of a `returns_values` bool, making page/column state unrepresentable for non-row-returning queries (#93)",
				]
			}
		]
	},
	{
		version: "0.27.0",
		date: "2026-06-07",
		tagUrl: "https://github.com/remcostoeten/dora/releases/tag/v0.27.0",
		groups: [
			{
				name: "Features",
				items: [
				"add multi-provider AI support for OpenAI, Anthropic, Gemini, Groq, and Ollama",
				"add encrypted API key storage, provider/model selection, and usage history",
				"add in-app Ollama setup flow with installer, runtime helpers, and model management",
				"feed live table indexes into assistant schema context",
				"extract Dora Studio into `@dora/studio` for desktop and marketing web demo",
				"render shared Studio at `/app` and refresh marketing landing with live demos and release-aware downloads",
				"add `Ctrl+Shift+B` to toggle the AI assistant from the Studio keyboard flow",
				]
			},
			{
				name: "Bug Fixes",
				items: [
				"preserve high-precision numeric values and BIGINTs during cell editing",
				"fix typed Postgres/SQLite cell edit and add-record binding behavior",
				"improve credential-store recovery with OS-aware keyring install actions",
				]
			},
			{
				name: "Refactoring",
				items: [
				"move reusable Studio experience into `packages/studio`",
				"rebuild marketing app-demo framing, theme polish, and deployment metadata",
				]
			},
			{
				name: "CI/CD",
				items: [
				"harden release automation with generated notes, post-release changelog sync, and package-manager fan-out",
				"bump release line to 0.27.0 across root, desktop, Tauri, and Cargo manifests",
				]
			}
		]
	},
	{
		version: "0.26.5",
		date: "2026-05-28",
		tagUrl: "https://github.com/remcostoeten/dora/releases/tag/v0.26.5",
		groups: [
			{
				name: "Bug Fixes",
				items: [
				"improve connection UX and Groq chat mode handling",
				]
			},
			{
				name: "CI/CD",
				items: [
				"extend asset poll budget for packaging workflows to 30 minutes",
				]
			},
			{
				name: "Other",
				items: [
				"Dora follow-up stability and UI fixes",
				]
			},
			{
				name: "Refactoring",
				items: [
				"redesign connection switcher with inline delete, settings panel, and sidebar polish",
				]
			}
		]
	},
	{
		version: "0.26.4",
		date: "2026-05-21",
		tagUrl: "https://github.com/remcostoeten/dora/releases/tag/v0.26.4",
		groups: [
			{
				name: "Bug Fixes",
				items: [
				"bump version files in package/tauri/cargo before tagging",
				]
			},
			{
				name: "Chores",
				items: [
				"automate package publishing",
				"add generate:releasetext script",
				"use git-cliff for release text generation",
				"add release script that auto-bumps, tags, and generates release text",
				"release script now auto-pushes and creates GitHub release",
				"fix release script to push tag separately",
				]
			},
			{
				name: "Features",
				items: [
				"show all by default, move logs/terminal to bottom panel, pass tail param through",
				"show all by default, move logs/terminal to bottom panel… (#71)",
				"structured SQL responses, dry run, syntax highlighting (#72)",
				]
			}
		]
	},
	{
		version: "0.26.2",
		date: "2026-05-20",
		tagUrl: "https://github.com/remcostoeten/dora/releases/tag/v0.26.2",
		groups: [
			{
				name: "Bug Fixes",
				items: [
				"extract linux tarball binary from tauri-built .deb",
				]
			}
		]
	},
	{
		version: "0.26.1",
		date: "2026-05-18",
		tagUrl: "https://github.com/remcostoeten/dora/releases/tag/v0.26.1",
		groups: [

		]
	},
	{
		version: "0.26.0",
		date: "2026-05-17",
		tagUrl: "https://github.com/remcostoeten/dora/releases/tag/v0.26.0",
		groups: [
			{
				name: "Bug Fixes",
				items: [
				"cast UPDATE value to column type during cell edits",
				"preserve JSON shape when editing object cells",
				]
			},
			{
				name: "CI/CD",
				items: [
				"add one-shot tag-create workflow",
				]
			},
			{
				name: "Chores",
				items: [
				"update dora to 0.25.0",
				"fix source URL to use v0.25.1 release tag",
				"update dora to 0.25.1",
				"regenerate Tauri bindings",
				"prune stale apps/db-tester entries from bun.lock",
				]
			},
			{
				name: "Features",
				items: [
				"pooler-compatible simple-query mode and pooler detection",
				"pooler-compatible mode toggle in connection form",
				"structured SQL responses, dry run, syntax highlighting, mock backend",
				"dedicated settings workspace replacing popover",
				]
			},
			{
				name: "Performance",
				items: [
				"backfill exact row counts when planner estimate is zero",
				]
			}
		]
	},
	{
		version: "0.25.2",
		date: "2026-05-17",
		tagUrl: "https://github.com/remcostoeten/dora/releases/tag/v0.25.2",
		groups: [
			{
				name: "Bug Fixes",
				items: [
				"install pinned bun archive path",
				"pin compatible bun archive",
				"use compatible bun for install",
				"tolerate immutable release uploads",
				]
			},
			{
				name: "CI/CD",
				items: [
				"publish package manager artifacts safely",
				]
			}
		]
	},
	{
		version: "0.25.1",
		date: "2026-05-16",
		tagUrl: "https://github.com/remcostoeten/dora/releases/tag/v0.25.1",
		groups: [
			{
				name: "Bug Fixes",
				items: [
				"rewrite store with useReducer to fix concurrent-mode state update bug",
				"remove nested button, use div+sibling-buttons for tab pills",
				"add skip-first-row and stop-on-error toggles to import dialog",
				"guard empty import, clear file input on close, memoize nonPKColumns",
				"FK schema-qualified navigation, CSV file size guard",
				"use --user flag for flatpak remote-add and install on GitHub Actions",
				]
			},
			{
				name: "CI/CD",
				items: [
				"add Flatpak publish workflow",
				]
			},
			{
				name: "Chores",
				items: [
				"update dora to 0.2.0",
				"bump version to 0.25.0, add changelog entry",
				]
			},
			{
				name: "Documentation",
				items: [
				"add v0.25 PRD — tabs, FK drill-down, CSV import",
				"add v0.25 implementation plan (9 tasks, tabs + FK + CSV)",
				"add v0.25.0 changelog entry to CHANGELOG.md and fix commit ref in sidebar data",
				]
			},
			{
				name: "Features",
				items: [
				"chat-style AI assistant sidebar (#63)",
				"add tab context store with 12-tab cap",
				"add TabBar component with close and middle-click support",
				"wire TabsProvider, TabBar, and openTab into Index.tsx",
				"plumb FK metadata into ColumnDefinition and enrich columns in DatabaseStudio",
				"add FK drill-down icon, opens referenced table in new tab",
				"add RFC 4180 CSV parser and column mapping utilities",
				"add CSV import dialog with preview, column mapping, and progress",
				"Dora v0.25.0 — Multi-Table Tabs, FK Drill-Down & CSV Import",
				]
			}
		]
	},
	{
		version: "0.2.2",
		date: "2026-05-15",
		tagUrl: "https://github.com/remcostoeten/dora/releases/tag/v0.2.2",
		groups: [
			{
				name: "Bug Fixes",
				items: [
				"use analytics ingestion endpoint",
				"use custom analytics ingestion domain",
				"align database studio headers",
				]
			},
			{
				name: "CI/CD",
				items: [
				"allow manual dispatch for a specific release tag",
				]
			},
			{
				name: "Features",
				items: [
				"centralize analytics providers",
				"add native dora AUR packaging and v0.2.0 updates (#62)",
				]
			},
			{
				name: "Other",
				items: [
				"detect pgbouncer=true flag and plumb use_simple_query",
				]
			}
		]
	},
	{
		version: "0.0.117",
		date: "2026-05-01",
		tagUrl: "https://github.com/remcostoeten/dora/releases/tag/v0.0.117",
		groups: [
			{
				name: "Bug Fixes",
				items: [
				"git-cliff config and workflow to generate proper release notes",
				]
			}
		]
	},
	{
		version: "0.0.116",
		date: "2026-05-01",
		tagUrl: "https://github.com/remcostoeten/dora/releases/tag/v0.0.116",
		groups: [
			{
				name: "Features",
				items: [
				"auto-generate release notes with git-cliff",
				]
			}
		]
	},
	{
		version: "0.0.113",
		date: "2026-05-01",
		tagUrl: "https://github.com/remcostoeten/dora/releases/tag/v0.0.113",
		groups: [
			{
				name: "Features",
				items: [
				"update desktop app and add Homebrew Cask integration",
				]
			}
		]
	},
	{
		version: "0.0.112",
		date: "2026-04-30",
		tagUrl: "https://github.com/remcostoeten/dora/releases/tag/v0.0.112",
		groups: [
			{
				name: "Testing",
				items: [
				"update desktop tests for schema visualizer release",
				]
			}
		]
	},
	{
		version: "0.0.111",
		date: "2026-04-30",
		tagUrl: "https://github.com/remcostoeten/dora/releases/tag/v0.0.111",
		groups: [
			{
				name: "Chores",
				items: [
				"release v0.0.111",
				]
			},
			{
				name: "Features",
				items: [
				"addd schema visualizer",
				"addd schema visualizer (#61)",
				]
			},
			{
				name: "Refactoring",
				items: [
				"apply consistent rustfmt styling across codebase and add row virtualizer for data grid components",
				]
			}
		]
	},
	{
		version: "0.0.110",
		date: "2026-04-27",
		tagUrl: "https://github.com/remcostoeten/dora/releases/tag/v0.0.110",
		groups: [
			{
				name: "Bug Fixes",
				items: [
				"disable transparent windows to prevent WebKit/Wayland crash",
				]
			},
			{
				name: "Documentation",
				items: [
				"add schema visualizer + AI SQL to README, bump download links to 0.0.109",
				]
			},
			{
				name: "Features",
				items: [
				"animated edges, theme-aware colors, search autocomplete",
				"chained schema-aware autocomplete",
				"multi-tab console and async row count",
				]
			}
		]
	},
	{
		version: "0.0.109",
		date: "2026-04-25",
		tagUrl: "https://github.com/remcostoeten/dora/releases/tag/v0.0.109",
		groups: [
			{
				name: "Bug Fixes",
				items: [
				"resolve .deb URL from release assets instead of constructing from tag version",
				"resolve CI lint, snap, AUR and winget failures",
				"escape ${srcdir}/${pkgdir} in PKGBUILD template literal",
				"use type instead of interface in analytics-dispatcher",
				]
			},
			{
				name: "Chores",
				items: [
				"add GPG public key for apt repo signing",
				"cleanup lib.rs debug guard and bindings.ts docstring noise",
				]
			},
			{
				name: "Documentation",
				items: [
				"add backend refactor checklist for remaining phases (5b, 5c, 4, 8)",
				"add product roadmap with tiered features and frontend checklist",
				"add keyboard shortcut UI spec using @remcostoeten/use-shortcut",
				]
			},
			{
				name: "Features",
				items: [
				"keyboard shortcut coverage (#52)",
				"query history improvements (#57)",
				"interactive ER diagram view (#58)",
				"schema-grounded AI ⌘I with Groq rotating-key provider (#59)",
				"AI encrypted key store + data-grid refactor (0.0.109) (#60)",
				]
			},
			{
				name: "Refactoring",
				items: [
				"split commands.rs by domain (phase 1) (#47)",
				"split storage.rs + typed Error enum (phases 2-3) (#48)",
				"scaffold WriteAdapter trait (phase 5a) (#49)",
				"add tracing + spans (phase 6) (#50)",
				"kill production unwraps, add clippy enforcement (phase 7) (#51)",
				"port mutation logic into WriteAdapter impls (#53)",
				"wire new error shape and type safety (phase 8)",
				"ConnectionRepository trait on AppState (phase 4)",
				"ConnectionRepository trait on AppState (phase 4) (#55)",
				"wire new error shape and type safety (phase 8) (#56)",
				"WatchAdapter trait per driver (phase 5c)",
				"WatchAdapter trait per driver (phase 5c) (#54)",
				]
			}
		]
	},
	{
		version: "0.0.107",
		date: "2026-04-19",
		tagUrl: "https://github.com/remcostoeten/dora/releases/tag/v0.0.107",
		groups: [
			{
				name: "Bug Fixes",
				items: [
				"add missing analytics-dispatcher, remove stale live-monitor test",
				]
			},
			{
				name: "Features",
				items: [
				"self-hosted apt repository — sudo apt install dora",
				]
			}
		]
	},
	{
		version: "0.0.106",
		date: "2026-04-19",
		tagUrl: "https://github.com/remcostoeten/dora/releases/tag/v0.0.106",
		groups: [
			{
				name: "Features",
				items: [
				"v0.0.106 — global live monitor, SSH tunnels, file exports, AUR binary",
				]
			}
		]
	},
	{
		version: "0.0.104",
		date: "2026-04-17",
		tagUrl: "https://github.com/remcostoeten/dora/releases/tag/v0.0.104",
		groups: [
			{
				name: "Bug Fixes",
				items: [
				"harden winget release workflow",
				"stabilize rust tests and snap release upload",
				]
			},
			{
				name: "Documentation",
				items: [
				"sync embedded homebrew tap",
				]
			},
			{
				name: "Features",
				items: [
				"allow record editing",
				]
			}
		]
	},
	{
		version: "0.0.103",
		date: "2026-04-12",
		tagUrl: "https://github.com/remcostoeten/dora/releases/tag/v0.0.103",
		groups: [
			{
				name: "Bug Fixes",
				items: [
				"react err",
				"run snap workflow in destructive mode",
				"adopt snap metadata from build part",
				"skip release upload on manual snap publish",
				]
			},
			{
				name: "Chores",
				items: [
				"update snap workflow, README, and snapcraft for MySQL support",
				"update snap workflow, README, and snapcraft for MySQL support (#46)",
				"opt snap workflow into node 24 actions",
				]
			},
			{
				name: "Features",
				items: [
				"Add MySQL connectivity support and testing companion prompt",
				"Add MySQL connectivity support (#43)",
				"add mysql connectivity  (#44)",
				"mysql connectivity and add homebrew install (#45)",
				]
			},
			{
				name: "Other",
				items: [
				"cut v0.0.103",
				]
			}
		]
	},
	{
		version: "0.0.102",
		date: "2026-04-05",
		tagUrl: "https://github.com/remcostoeten/dora/releases/tag/v0.0.102",
		groups: [
			{
				name: "Bug Fixes",
				items: [
				"run snapcraft with sudo in CI",
				"use bun run in snap build scriptlet",
				"build snap binary with cargo release",
				]
			},
			{
				name: "Other",
				items: [
				"prepare v0.0.102",
				]
			}
		]
	},
	{
		version: "0.0.101",
		date: "2026-04-05",
		tagUrl: "https://github.com/remcostoeten/dora/releases/tag/v0.0.101",
		groups: [
			{
				name: "Documentation",
				items: [
				"add homebrew installation section",
				]
			},
			{
				name: "Features",
				items: [
				"add homebrew tap for dora",
				]
			},
			{
				name: "Other",
				items: [
				"prepare v0.0.101",
				]
			}
		]
	},
	{
		version: "0.1.0",
		date: "2026-04-04",
		tagUrl: "https://github.com/remcostoeten/dora/releases/tag/v0.1.0",
		groups: [
			{
				name: "Bug Fixes",
				items: [
				"change build target to esnext to resolve CI esbuild transform error",
				]
			}
		]
	},
	{
		version: "0.0.100",
		date: "2026-04-04",
		tagUrl: "https://github.com/remcostoeten/dora/releases/tag/v0.0.100",
		groups: [
			{
				name: "Bug Fixes",
				items: [
				"use valid GitHub Actions commit SHAs",
				"use stable branch for rust-toolchain to avoid parsing issues",
				]
			},
			{
				name: "Chores",
				items: [
				"pin GitHub Actions to specific commit SHAs",
				]
			}
		]
	},
	{
		version: "0.0.98",
		date: "2026-04-04",
		tagUrl: "https://github.com/remcostoeten/dora/releases/tag/v0.0.98",
		groups: [
			{
				name: "Chores",
				items: [
				"checkpoint current workspace before live monitor refactor",
				"remove bloat",
				"add all uncommitted changes",
				"release v0.0.98",
				]
			},
			{
				name: "Documentation",
				items: [
				"add animated WEBP showcase to README",
				]
			},
			{
				name: "Features",
				items: [
				"add live database updates",
				]
			},
			{
				name: "Refactoring",
				items: [
				"replace frontend live polling with backend live monitor manager",
				]
			}
		]
	},
	{
		version: "0.0.97",
		date: "2026-02-20",
		tagUrl: "https://github.com/remcostoeten/dora/releases/tag/v0.0.97",
		groups: [
			{
				name: "Other",
				items: [
				"UX polish, shortcuts & cleanup",
				"cut v0.0.97 with type-safety fixes and docker updates",
				]
			}
		]
	},
	{
		version: "0.0.96",
		date: "2026-02-17",
		tagUrl: "https://github.com/remcostoeten/dora/releases/tag/v0.0.96",
		groups: [
			{
				name: "Features",
				items: [
				"mouse-promo recorder and accessibillity",
				"finalize Windows Tauri dev and CLI automation",
				"merge Windows Tauri dev, libsql-rusqlite, and CLI automation",
				]
			}
		]
	},
	{
		version: "0.0.95",
		date: "2026-02-09",
		tagUrl: "https://github.com/remcostoeten/dora/releases/tag/v0.0.95",
		groups: [
			{
				name: "Bug Fixes",
				items: [
				"repair changelog popover render and restore scroll",
				"use supported intel macOS runner",
				]
			},
			{
				name: "Chores",
				items: [
				"prepare v0.0.95 and refresh changelog metadata",
				]
			},
			{
				name: "Features",
				items: [
				"add rpm msi and intel macOS build target",
				]
			}
		]
	},
	{
		version: "0.0.94",
		date: "2026-02-09",
		tagUrl: "https://github.com/remcostoeten/dora/releases/tag/v0.0.94",
		groups: [
			{
				name: "Bug Fixes",
				items: [
				"resolve failing tests and rust compile issues",
				"unblock rust tests in github actions",
				"add postgres initdb bin path for pgtemp tests",
				"resolve pipeline failures (#32)",
				"restore cross-platform release flow and prep v0.0.94 (#33)",
				"use vcpkg sqlite on windows and avoid sqlite symbol clashes",
				"export vcpkg sqlite library paths for windows linker",
				]
			},
			{
				name: "Documentation",
				items: [
				"update README with v0.0.93 download links and installation instructions",
				]
			}
		]
	},
	{
		version: "0.0.93",
		date: "2026-02-06",
		tagUrl: "https://github.com/remcostoeten/dora/releases/tag/v0.0.93",
		groups: [
			{
				name: "Bug Fixes",
				items: [
				"docker view sort error and save accumulated work",
				"resolve syntax error in database-studio.tsx",
				"replace native dialogs with shadcn components and clean up debug logs",
				"pass prebuild checks and fix production build",
				"correct rust-toolchain action reference and package.json syntax",
				]
			},
			{
				name: "Chores",
				items: [
				"cleanup unused files and dependencies (audit)",
				"optimize insert_row allocation (backend round 2)",
				"snapshot before full system audit",
				"prepare v0.0.93 with comprehensive changelog",
				]
			},
			{
				name: "Features",
				items: [
				"add cleanup audit tools",
				"performance optimizations (bundle split, zero-flash pagination, efficient IPC)",
				"Add Monaco Editor workers and LSP utilities to enhance code editing features.",
				"replace native alerts with shadcn and align bottom bars",
				"error handling, query history, and release-ready UI polish",
				"add custom shortcuts UI with persistence and dynamic bindings",
				"Add light/dark theme toggle, SQL snippet saving, and refactor connection snippet display.",
				"add typo detection with fuzzy matching",
				"add Drizzle-aware typo diagnostics with fuzzy suggestions",
				"integrate Drizzle-aware typo diagnostics across UI components",
				]
			},
			{
				name: "Performance",
				items: [
				"efficient IPC layer, bundle split, monaco workers offload (#28)",
				]
			}
		]
	},
	{
		version: "0.0.925",
		date: "2026-01-24",
		tagUrl: "https://github.com/remcostoeten/dora/releases/tag/v0.0.925",
		groups: [
			{
				name: "Bug Fixes",
				items: [
				"improve sidebar dragging physics and animations",
				"sidebar resize now follows mouse in real-time instead of snapping",
				"propagate connection errors in test_connection",
				"Strip unsupported channel_binding parameter from PostgreSQL connection strings",
				"resolve table data loading and sort crash",
				"address CodeRabbit PR review comments",
				"lsp build issues",
				]
			},
			{
				name: "CI/CD",
				items: [
				"upgrade runners to Blacksmith for 2x faster performance",
				"revert to standard ubuntu-latest runners",
				]
			},
			{
				name: "Chores",
				items: [
				"cleanup dead/duplicate code files",
				"restructure frontend core",
				"save pending changes",
				"finalize resize and cleanup docs",
				"cleanup project structure (remove unused FE, rename docs, move test queries)",
				"misc fixes and improvements across desktop and api-docs",
				"prepare for release v0.0.9 - code style cleanup and fixes",
				"remove redundant api-docs project and move docs to root",
				"prepare release 0.0.92",
				"bump version to 0.0.925",
				]
			},
			{
				name: "Documentation",
				items: [
				"update readme with beta feature status",
				"refine readme features and roadmap",
				]
			},
			{
				name: "Features",
				items: [
				"add auto-fill, typo detection & validation for connection strings",
				"add autocomplete input with keyboard navigation",
				"refresh splash screen design",
				"add database-backed settings with theme persistence",
				"add sql-builder, resize-handle, UI improvements and border fixes",
				"add sql-builder, autocomplete and settings persistance (#1)",
				"implement accessible Label component and replace native labels",
				"implement AES-GCM encryption for connection storage",
				"implement get_connection method",
				"add context menu to saved connections",
				"add connection history tracking with filters",
				"enhance connections UI and data table UX with favorites, timestamps, sorting, pagination",
				"Implement command palette with global command system and persistent keyboard shortcuts.",
				"enhance connection string parsing, improve shortcut management, and refine UI interactions",
				"add command palette UI and refactor URL query string construction.",
				"Implement command usage tracking and persistence, add new application commands, and enhance command palette sorting based on usage history.",
				"Implement command palette with global command system  (#4)",
				"add spreadsheet-like Table Browser with filtering, sorting, inline editing, and dry-run mode",
				"Implement dedicated table exploration view with a new `table-view` tab type and `TableBrowser` component.",
				"Implement schema visualization with React Flow and add back navigation to table browser.",
				"Implement core application structure, introduce shared UI components, and integrate Tauri commands for database management.",
				"Introduce unified header and logo components, refactor theme colors to hex/rgba, and add keyboard shortcuts for main view navigation.",
				"Introduce unified header and logo components, refactor theme co… (#6)",
				"Add Monaco Editor and Switchable SQL Editor components",
				"add database adapter trait, mutation API, and enhanced schema introspection",
				"add LibSQL database support for local and remote Turso connections",
				"add LibSQL database parsing and execution support",
				"Reorganize project structure and migrate existing components to a new `_old` directory layout.",
				"major backend upgrade",
				"update docs dependencies, add new desktop icons, and remove old Tauri database files.",
				"integrate AI service types with Specta",
				"expose and finalize SSH tunnel module",
				"implement Specta integration and generate TypeScript client",
				"add duplicate_row command for context menu actions",
				"implement snippet library with pre-made and user-created snippets",
				"introduce snippet categories for improved organization and filtering",
				"Backend API V2 & Specta Integration (#8)",
				"run queries via rust",
				"implement data provider pattern and refactor sidebar",
				"implement better web mock view",
				"implement data provider pattern for web mock view (#10)",
				"improve accessibillity for data viewer",
				"implement rust binding in FE",
				"implement missing desktop features",
				"add user theme and setting persistance",
				"add user theme and setting persistence (#11)",
				"implement SSH tunnel configuration for database connections",
				"SSH Tunnel configuration for database connections (#12)",
				"Schema Management (DDL) feature (#13)",
				"centralization keyboard shortcuts (#14)",
				"Undo/redo functionality, editor themes,  DDL retrieval & dry mode (#15)",
				"implement changelog panel and cell improvements",
				"release version 0.0.9 by updating tauri config, adding release notes, and updating the README.",
				"Implement bulk edit and set null functionalities, and refactor … (#16)",
				"Redesign and reposition the DemoBanner as a fixed, floating component in the bottom-right corner.",
				"add Midnight, Forest, Claude Light, and Claude Dark themes with… (#19)",
				"Add new technical and vintage font options, remove density setting, and update Vercel deployment configurations.",
				"custom drizzle DSL LSP for monaco covering 100% of spec",
				"implement comprehensive test infrastructure\\n\\n- Add test scripts to package.json files\\n- Configure Turbo build to depend on tests\\n- Create GitHub Actions CI workflow with Postgres service\\n- Migrate Rust tests to proper integration tests structure\\n- Export Rust modules for testing access",
				"implement testing infrastructure",
				"implement testing suite and floating selecton bar  (#20)",
				"sync monaco theme with ui switcher (#21)",
				"typo detection algorithm and testing infrastructure (#22)",
				"implement branding & LSP promotion helpers (#23)",
				"Implement theme synchronization, URL state management, and enhance data grid context menu handling. (#24)",
				"implement promotional LSP demo mode",
				"Introduce recording mode with configurable UI elements, environment variable support, and a visual overlay.",
				"update app logo, favicon, and sidebar branding",
				"Implement theme synchronization, URL state management, and enhance data grid context menu handling.",
				"Enhance table info dialog with PostgreSQL validation and SQL escaping, synchronize data grid focused cell, and simplify cell context menu API.",
				"Distinguish context menu kind in URL state, truncate large selected cell sets, and validate URL-derived table states against current table dimensions.",
				"introduce new application sidebar and integrate it with the database studio, including an animated toggle icon.",
				"implement docker container manager mvp (#25)",
				"enhance Docker container management with advanced creation options, connection snippets, compose export, and database seeding (#26)",
				"add Tauri dialog plugin and Zustand, and ignore local environment files in gitignore",
				"release 0.0.925 - docker manager, data seeder, build fixes",
				]
			},
			{
				name: "Other",
				items: [
				"restore security and label features while keeping sidebar animations",
				"implement domain architecture (#5)",
				]
			},
			{
				name: "Refactoring",
				items: [
				"reorganize components and enhance tabs with context menu, dnd, and pin support",
				"rename component-specific type aliases to Props and remove associated refactoring scripts.",
				"update metadata structs, fix parser compatibility, and resolve types",
				"Simplify web demo auto-connection logic to generically auto-select the first table.",
				]
			},
			{
				name: "Testing",
				items: [
				"add comprehensive encryption tests",
				]
			}
		]
	}
]
