export type ForeignKeyRef = {
	referencedTable: string
	referencedColumn: string
	referencedSchema?: string
}

export type ColumnDefinition = {
	name: string
	type: string
	nullable: boolean
	primaryKey: boolean
	foreignKey?: ForeignKeyRef
	/**
	 * Closed set of values the database constrains this column to (a Postgres
	 * `enum`, a MySQL `ENUM`, or a `CHECK (col IN (...))` list). When present,
	 * the grid edits the cell with a dropdown instead of a free-text input.
	 */
	allowedValues?: string[]
	/**
	 * The database fills this column in when an insert omits it: an
	 * auto-increment/identity column or one with a DEFAULT expression. Only set
	 * once the table's schema has been introspected; absent means unknown.
	 */
	autoGenerated?: boolean
}

export type TableData = {
	columns: ColumnDefinition[]
	rows: Record<string, unknown>[]
	totalCount: number
	executionTime: number
}

export type SortDescriptor = {
	column: string
	direction: 'asc' | 'desc'
}

export type FilterOperator = 'eq' | 'neq' | 'gt' | 'gte' | 'lt' | 'lte' | 'ilike' | 'contains'

export type FilterDescriptor = {
	column: string
	operator: FilterOperator
	value: unknown
}

/** How multiple filter conditions are joined together. */
export type FilterConjunction = 'AND' | 'OR'

/**
 * A single leaf condition inside a filter group. Identical shape to
 * {@link FilterDescriptor}; aliased for clarity within the group model.
 */
export type FilterCondition = FilterDescriptor

/**
 * A nestable group of filter conditions joined by a single logic operator.
 * The root group defaults to `AND`. Nesting is supported one level deep
 * (i.e. two levels total): a child group may contain only leaf conditions.
 * Fully serializable for tab persistence (#98).
 */
export type FilterGroup = {
	logic: FilterConjunction
	conditions: Array<FilterCondition | FilterGroup>
}

/** Narrows a group member to a nested group (vs a leaf condition). */
export function isFilterGroup(node: FilterCondition | FilterGroup): node is FilterGroup {
	return typeof (node as FilterGroup).logic === 'string' && Array.isArray((node as FilterGroup).conditions)
}

export type TableQueryParams = {
	tableId: string
	limit: number
	offset: number
	sort?: SortDescriptor
	filters?: FilterDescriptor[]
	conjunction?: FilterConjunction
	/**
	 * Structured AND/OR filter tree. When present it supersedes the flat
	 * `filters`/`conjunction` pair. The flat fields are kept for backward
	 * compatibility with persisted state.
	 */
	filterGroup?: FilterGroup
}

export type ViewMode = 'content' | 'structure' | 'chart'

export type PaginationState = {
	limit: number
	offset: number
} // Keeping for compat, though could be merged
